### ISSUE TITLE
Playlists broken in rewrite.

### ISSUE THREAD

**Issue by Tetracyl** [WarHammer414/erela.js#33]
Playlists seem to be erroring in the rewrite. This error pops up when playing playlists on Youtube, Soundcloud and Bandcamp:

```
TypeError: Cannot read property 'info' of undefined
    at Manager.<anonymous> (/root/ear_tensifier/node_modules/@tetracyl/erela.js/dist/structures/Manager.js:108:49)
    at Generator.next (<anonymous>)
    at fulfilled (/root/ear_tensifier/node_modules/@tetracyl/erela.js/dist/structures/Manager.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by Tetracyl** [comment]
Fixed: #34
